[package]
name = "starryhoot-utils"
version = "0.0.1"
description = "StarryHoot Utilities Lib"
authors = ["@rustytsuki"]
edition = "2021"

[lib]
name = "utils"
crate-type = ["lib"]

[features]
# this feature is used for production builds
# DO NOT REMOVE!!
production = ["dep:rust-embed"]

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
rust-embed = { version = "8.2", features = ["include-exclude"], optional = true }

[build-dependencies]
downloader = "0.2.7"
tar = "0.4"
flate2 = "1.0"
zip-extract = "0.2.1"
