name: On New Tag Publish

on:
    push:
        tags:
            - 'v*'

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    # call-publish-windows:
    #     uses: ./.github/workflows/publish-windows.yml
    #     with:
    #         tag: ${{ github.ref_name }}
    #     secrets:
    #         STARRYHOOT_RELEASE: ${{ secrets.STARRYHOOT_RELEASE }}

    # call-publish-linux:
    #     uses: ./.github/workflows/publish-linux.yml
    #     with:
    #         tag: ${{ github.ref_name }}
    #     secrets:
    #         STARRYHOOT_RELEASE: ${{ secrets.STARRYHOOT_RELEASE }}

    # call-publish-mac:
    #     uses: ./.github/workflows/publish-mac.yml
    #     with:
    #         tag: ${{ github.ref_name }}
    #     secrets:
    #         STARRYHOOT_RELEASE: ${{ secrets.STARRYHOOT_RELEASE }}

    call-publish-www:
        uses: ./.github/workflows/publish-www.yml
        with:
            tag: ${{ github.ref_name }}
        secrets:
            STARRYHOOT_RELEASE: ${{ secrets.STARRYHOOT_RELEASE }}
