name: Publish Mac

on:
    workflow_dispatch:
        inputs:
            tag:
                description: 'Publish Mac'
                required: true
                type: string

    workflow_call:
        inputs:
            tag:
                description: 'Publish Mac'
                required: true
                type: string
        secrets:
            STARRYHOOT_RELEASE:
                required: true

jobs:
    build-mac:
        runs-on: macos-14

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.inputs.tag }}

            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  target: |
                    x86_64-apple-darwin
                  override: true

            - name: Install dependencies
              run: |
                  cd app && npm ci && cd ..
                  cd deploy && npm ci && cd ..
                  cd web && npm ci && cd ..

            - name: Extract tag version
              id: extract_version
              env:
                  TAG_NAME: ${{ inputs.tag || github.event.inputs.tag }}
              run: |
                  echo "TAG_NAME=$TAG_NAME" >> "$GITHUB_ENV"

                  VERSION="${TAG_NAME#v}"
                  IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

                  if [ -z "$MAJOR" ] || [ -z "$MINOR" ] || [ -z "$PATCH" ]; then
                  echo "Invalid version format: $VERSION"
                  exit 1
                  fi

                  echo "VERSION_MAJOR=$MAJOR" >> "$GITHUB_ENV"
                  echo "VERSION_MINOR=$MINOR" >> "$GITHUB_ENV"
                  echo "VERSION_PATCH=$PATCH" >> "$GITHUB_ENV"

            - name: Run publish script for Mac
              working-directory: ./deploy
              env:
                  GH_TOKEN: ${{ secrets.STARRYHOOT_RELEASE }}
                  VERSION_MAJOR: ${{ env.VERSION_MAJOR }}
                  VERSION_MINOR: ${{ env.VERSION_MINOR }}
                  VERSION_PATCH: ${{ env.VERSION_PATCH }}
              run: |
                  npm run mac:publish
