name: Publish Windows

on:
    push:
        tags:
            - 'v*'

jobs:
    build-win:
        runs-on: windows-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install Rust toolchain (x64)
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  target: x86_64-pc-windows-msvc
                  override: true

            - name: Install dependencies
              run: |
                  cd app && npm ci && cd ..
                  cd deploy && npm ci && cd ..
                  cd web && npm ci && cd ..

            - name: Extract tag version
              id: extract_version
              run: |
                  echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
                  VERSION=${GITHUB_REF#refs/tags/v}
                  IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
                  echo "VERSION_MAJOR=$MAJOR" >> $GITHUB_ENV
                  echo "VERSION_MINOR=$MINOR" >> $GITHUB_ENV
                  echo "VERSION_PATCH=$PATCH" >> $GITHUB_ENV

            - name: Run publish script for Windows
              working-directory: ./deploy
              env:
                  GH_TOKEN: ${{ secrets.STARRYHOOT_RELEASE }}
                  VERSION_MAJOR: ${{ env.VERSION_MAJOR }}
                  VERSION_MINOR: ${{ env.VERSION_MINOR }}
                  VERSION_PATCH: ${{ env.VERSION_PATCH }}
              run: |
                  npm run publish:win
