name: Publish Windows

on:
    push:
        tags:
            - 'v*'

jobs:
    build-win:
        runs-on: windows-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install Rust toolchain (x64)
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  target: x86_64-pc-windows-msvc
                  override: true

            - name: Install dependencies
              run: |
                  cd app && npm ci && cd ..
                  cd deploy && npm ci && cd ..
                  cd web && npm ci && cd ..

            - name: Run publish script for Windows
              working-directory: ./deploy
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  npm run publish:win
